import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import HomeScreen from '../src/FRONTEND/VIEWS/HomeScreen'
import { GetStaticProps } from 'next'

const Home = ({projects}: any) => {
  return (
    <>
      <Head>
        <title>Ellah Nzikoba</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/0a108ab6f7.js" crossOrigin="anonymous" async></script>
      </Head>
      <main >
        <HomeScreen projects={projects} />
      </main>
    </>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async () => {
  const {projects} = await import("../data/sample_data.json", { assert: { type: "json" } })

  console.log(projects)
  return {
    props: {
      projects: projects

    }
  }

}
